# Site settings
title: Evan Dana's CV
description: Evan Dana's CV
favicon: /assets/img/edana-professional.jpg
baseurl: ""
url: http://evandana.github.io
rss_url: /pages/atom.xml
google_analytics: UA-6306273-2
resumelink: /assets/Evan-Dana__Public-Resume.pdf


# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Evan Dana
  title: Sr. Software Engineer
  address: Boston, MA
  email: userhatestogetspam@gmail.com
  link: http://evandana.com
  weibo:
  github: evandana
  linkedin: evandana
  twitter: evandana
  gavatar: /assets/img/edana-professional.jpg
  stackoverflow:
#  stackoverflow: 4582127
  intro: 
      firstline: >
        Lead Software Engineer with a focus on <a href="#work-sample-auction-app" title="Jump to Auction App (Work Sample)">architecting successful web experiences</a>. 
      description: >
        Approaches challenges with <a href="#activity-november-project" title="Jump to November Project (Activity)">engaging energy and passion</a>, 
        engineering <a href="#work-sample-evandanadotcom" title="Jump to Evandana.com (Work Sample)">efficient tooling, processes</a>, and <a href="#workHistory-sapient" title="Jump to Publicis.Sapient (Work History)">organization to benefit the project and team</a>.
        <a href="#activity-ga-instructor" title="Jump to GA Instructor (Activities)">Articulate technical</a> and cross-domain communication enhanced by <a href="#education-history-rit" title="Jump to RIT (Education History)">design background</a>.
  workSamples:
    - ahope:
      id: ahope
      title: Non-profit Intake App
      description: >
        Leading a team to create an intake app for a local non-profit. 
        Creating and navigating requirements from stakeholders, including secure data storage and transfer with Google Cloud services.
        Managing a small group of software engineers who are donating time for this project, ensuring coordinated efforts, timely delivery, and continued engagement.
      features: 
        - feature1: 
          text: Form submission, contact profile search and update, and reports
        - feature1:
          text: Websockets and REST, React / Redux
        - feature1: 
          text: Secure sign-in using Google OAuth
        - feature1: 
          text: Parse API for server and database interface on Google Cloud
      icon: mouse-pointer
      technologies: "ReactJS 15.1.x, Redux, Google Cloud, Parse, WebSockets, Material-UI, Google OAuth, ES6, Babel"
      link: https://github.com/evandana/keep-ahope
      completedyear: 2018
    - auctionapp:
      id: auction-app
      title: PMC Auction App
      description: >
        From concept through development to processing results, this live-bidding auction and raffle ticket web app exceeded expectations for learning experiences and funds raised. 
        Working with one other developer, we started with domain models, UX whiteboarding, framework choices, and hosting discussions.
        <br/><br/>
        <a href="https://pmc-2018-demo.firebaseapp.com" target="_BLANK">Try the demo-version <i class="fa fa-external-link"></i></a> using dummy data. 
      features: 
        - feature1: 
          text: 'Live bidding: websockets, React / Redux'
        - feature1: 
          text: Secure sign-in using Google OAuth
        - feature1: 
          text: Enforced bidding rules 
        - feature1: 
          text: Database and hosting using Firebase.io
      icon: mouse-pointer
      technologies: "ReactJS 15.1.x, Redux, WebSockets, Firebase.io, Material-UI, Google OAuth, ES6, Babel, Domain Modeling"
      link: https://pmc-2018-demo.firebaseapp.com
      completedyear: 2018
    - streamcorrelation:
      id: streamcorrelation 
      title: Stream Correlation
      collapsed: true
      description: "Individual hackathon project intending to address the question: \"What other ways can a web app add value to an HMI (human-machine interface) dashboard?\""
      features: 
        - feature: 
          text: "Node service generates semi-random data into N streams and publishes values over WebSocket connection"
        - feature: 
          text: "Node service subscribes to data generator, stores subset of data, processes data for correlation, and makes processed data available over WebSockets to client UI"
        - feature: 
          text: "Client UI subscribes to processed data service and shows corelation graph for any streams that correlate with the specified streams"
        - feature: 
          text: "Initialization and installation of the above three folders is handled simultaneously with shell script"
      icon: cogs
      technologies: "NodeJS, Polymer 2.0, WebSockets, Correlation Rank (NPM)"
      link: https://github.com/evandana/stream-correlation
      completedyear: 2017
  workHistory:
    - work1:
      id: ge
      company: General Electric | GE Digital
      location: Boston, MA
      title: Sr. Software Engineer
      started: 2016
      duration: 2016 &ndash; Present
      technologies: "ES6, Polymer, NodeJS, CI/CD, Hexagonal Architecture, Domain Modeling" 
      description: > 
        Delivered complex features in a timely manner, independently and through collaboration, with utmost attention to quality. 
        Exemplified best practices from coding patterns to agile methodologies.
        Translated requirements into manageable stories with clear and complete acceptance criteria, raising discussions early if needed.
        <br/><br/>    
        Mentored software engineers and presented on modern UI frameworks and patterns through the use of interactive programming session.
    - work1:
      id: sapient
      company: Publicis.Sapient | Sapient Consulting
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2013
      duration: 2013 &ndash; 2016
      technologies: "ES6, AngularJS 1.x, Aurelia, Agile, Atomic Design, JSPM, NodeJS, Continuous Integration, Hexagonal Architecture (server-side), Domain-Driven Development, Domain Modeling" 
      description: > 
        UI Lead and front-end developer with aptitude for team dynamics: group coordination, process efficiencies, and individual development. 
        Awarded recognition for Client-Focused Delivery after client feedback on project when leading FED with recently self-taught technology.
        <br/><br/>    
        Years of experience in UI lead role, conducting engaging technical presentations, and as technical liason for client and internal domain teams.
        Enforced code quality using best practices such as John DePapa's style guide and BEM on both Agile and Atomic approach projects. 
        Self-motivated and driven as exemplified by creation of D3.js library during bench time and initiation of effective team-building program.
        Advocate for code stability through unit, integration, functional, or automated visual-diff testing.
    - work1:
      company: Putnam Investments
      collapsed: true
      location: Boston, MA
      title: Javascript UI Developer 
      started: 2012
      duration: 2012 &ndash; 2013
      technologies: JavaScript (jQuery, Highcharts), CSS, HTML, Backbone.js, Modernizr, SVN
      description: >
        Extended current app by developing additional functionality and engaging UI with JavaScript. 
        Implemented significant contributions in an Agile team to achieve business goals. 
        Reached cross-browser functionality with collaborative discussions. 
    - work1:
      company: Innerscope Research Inc.
      collapsed: true
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2009
      duration: 2009 &ndash; 2012
      technologies: HTML, CSS, PHP, JavaScript, Photoshop, Illustrator
      description: >
        Architected, implemented, and optimized dynamic internal web sites under tight time constraints. Increased efficiency through process refinement and custom application development; reduced bottle-necks. Satisfied clients by researching technical solutions, advising on options, and implementing solutions. Effectively managed graphic design interns with clear instruction and judicious direction; initiated the graphic design intern program, complete with cumulative curriculum. Conceptualized, designed, and coordinated delivery of graphical needs: marketing material, graphical information, and interactive experiences.
    - work1:
      company: EC Boston
      collapsed: true
      location: Boston, MA
      title: Web Developer 
      started: 2009
      duration: 2009
      technologies: HTML, CSS, PHP, JavaScript, Adobe Contribute compatibility, Photoshop, Illustrator
      description: >
        Facilitated and increased conversion rates by establishing new branding and easily accessible information. 
        Worked closely with client to optimize content organization and modernize graphical feel for improved user experience. 
        Content updatable by client without markup. Site was live September 2009 &ndash; 20011.
    - work1:
      company: Crimson Life Sciences
      collapsed: true
      location: Boston, MA
      title: Process Engineer 
      started: 2009
      duration: 2009
      technologies: Java (apache.poi, javax.swing), Eclipse IDE, Microsoft Office (2001 &ndash; 2007), Mac and PC platforms
      description: >
        Delivered high ROI by automating Excel and Word document processing. 
        Thoroughly examined current manual processes; using diagrams and concise summary, discussed proposed solution with project stakeholders. 
        Achieved timely project completion through appropriate architecture and schedule planning. 
        Resulting desktop Java application eliminated unnecessary user interaction and maximized efficiency, accuracy and ease of use.
    - work1:
      company: Reebok International
      collapsed: true
      location: Canton, MA
      title: Graphic Designer & Process Engineer 
      started: 2007
      duration: 2007 &ndash; 2009
      technologies: "AppleScript, HTML, XML, CSS, PHP, FileMaker Pro, InDesign, Illustrator, Photoshop, Bridge"
      description: >
        Improved efficiency and accuracy of artwork-data workflow by authoring scripts to remove repetitive tasks. 
        Initiated projects to enhance data communication across groups. 
        Saved resources by in-house development of a dynamic departmental website for collateral viewing and organization; crafted simple update process with existing database. 
        Designed and built image- and data-intensive catalogs; coordinated and automated catalog production. 
  educationHistory:
    - rit:
      id: rit
      organization: Rochester Institute of Technology
      location: Rochester, NY
      degree: Bachelor
      major: Industrial Design
      completed: 2005
      duration: (2001 &ndash; 2005)
      description: >
        BFA in Industrial Design, GPA 3.84, highest honors. 
        <br/><br/>
        AAS in Graphic Design. 
        <br/>
        Concentration in conversational French. Technical concentrations in Mechanical and Manufacturing Technology.
    - extension:
      organization: Harvard Extension School
      location: Cambridge, MA
      description: >
        Mobile Operating Systems and Applications
        <br/><br/>
        Deep dive into hardware and software underlying Android and iOS operating sytems. 
        Covered spectrum of mobile landscape and considerations for design/development of web, native wrappers, and native apps.
        Final project: Android "deck of cards" workout app.
      completed: 2013
      duration: 2013 &ndash; 2013
    - coursera:
      organization: Coursera.org
      location: Stanford University Online
      description: >
        Enriched and expanded skills and understanding with classes: Introduction to Python & Model Thinking & Software Engineering for SaaS. 
        Courses included homework, lectures, and quizzes/exams. 
        <br/></br/>
        Topics covered: Python, Ruby on Rails, SQL, Amazon Web Services, version control with GIT, and cloud deployment with Heroku. 
        Earned a certificate of completion for listed classes.
      completed: 2014
      duration: (2012 &ndash; 2013)  
  activities:
    - activity:
      id: november-project
      location: Boston, MA
      title: Co-leader of November Project Boston
      started: 2013
      icon: bicycle
      duration: 2014 &ndash; 2015
      description: >
        November Project is a free-fitness movement with "tribes" in 30+ cities across the world, with Boston as the origin.
        <br/></br/>
        Developed comfort, ease, and power when speaking and writing for a large audience.
        Inspired self and others while designing, leading, coaching, and documenting workouts for 150-1500 athletes of all abilities.  
        With co-leaders, cultured strong relationships that included feedback cycles.
    - activity:
      id: ga-instructor
      location: General Assembly, MA
      title: D3.js Instructor 
      started: 2015
      icon: code
      duration: 2015
      description: >
        Engaged developers in an immersive and interactive two-night class: Introduction to D3.js. 
        Presented using a <a href="http://slides.com/evandana/d3-intro-3" target="_BLANK">follow-along slide deck<i class="fa fa-external-link"></i></a>
         with individually-editable code examples.
    - activity:
      hidden: true
      location: Boston, MA
      collapsed: false
      title: Co-leader and Webmaster of The Most Informal Running Club Ever (TMIRCE) 
      started: 2010
      icon: bicycle
      duration: 2010 &ndash; 2011
      description: >
        Cultivated welcoming community of runners through attitude modeling and directing activities. 
        Provided club necessities and member benefits through successfully managed sponsor relationships without losing sight of integrity. 
        Positioned club for success with engaging presentation of its social impact.
  REMOVE-THIS-TO-ENABLE-languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited Conversational
  programmingSkills:
    - skill2:
      name: "Frameworks: Polymer | React | Angular | Aurelia"
      percentage: 80%
      usefulness: expert
    - skill1:
      name: JavaScript/ES6
      percentage: 70%
      usefulness: expert
    - skill4:
      name: HTML5
      percentage: 70%
      usefulness: experienced
    - skill3:
      name: CSS3/SCSS
      percentage: 60%
      usefulness: experienced
    - skill3:
      name: Server-side
      percentage: 30%
      usefulness: proficient
  opensource:
      intro: Notable repos
      repos:
      - repo:
        name: AHOPE
        year: 2018
        link: https://github.com/evandana/keep-ahope
        description: Patient intake app created in partnership with GE Foundation
      - repo:
        name: Auction App
        year: 2018
        link: https://github.com/evandana/pmc-auction/tree/feature/2018
        description: Charitable-focused auction app including bucketed raffles
      - repo:
        name: Stream Correlation
        year: 2018
        link: https://github.com/evandana/stream-correlation
        description: Generate random data streams and show which ones are correlated
      - repo:
        name: Repo for this site
        year: 2018
        link: https://github.com/evandana/evandana.github.io
        description: Jekyll template with UX modifications
      - repo:
        name: Previous evandana.com
        year: 2018
        link: https://github.com/evandana/website-2012
        description: D3.JS, PHP, JavaScript, XML, XSLT, HTML5, CSS3, InDesign XML Workflow
