# Site settings
title: Evan Dana's CV
description: Evan Dana's CV
favicon: /assets/img/edana-professional.jpg
baseurl: ""
url: http://evandana.github.io
rss_url: /pages/atom.xml
google_analytics: UA-6306273-2

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Evan Dana
  title: JavaScript Developer
  address: Boston, MA
  email: userhatestogetspam@gmail.com
  link: http://evandana.com
  weibo:
  github: evandana
  linkedin: evandana
  twitter: evandana
  gavatar: /assets/img/edana-professional.jpg
  stackoverflow:
#  stackoverflow: 4582127
  intro: 
      title: Something here
      description: something else goes here and here and here
  workSamples:
    - auctionapp:
      title: PMC Auction App
      description: "From concept through development to processing results, this live-bidding auction web app exceeded expectations for learning experiences and funds raised. Working with one other developer, we started with domain models, UX whiteboarding, framework choices, and hosting discussions.<br/><br/>Try the <a href=\"https://auction-demo.firebaseapp.com\" target=\"_BLANK\">demo-version</a> using dummy data." 
      features: 
        - feature1: 
          text: Live bidding using Websockets.io, ReactJS, and Redux
        - feature1: 
          text: Secure sign-in using Google OAuth
        - feature1: 
          text: Enforced bidding rules 
        - feature1: 
          text: Database and hosting using Firebase.io

        - feature1: 
          text: Remove Donate links
        - feature1: 
          text: Update intro page explaining it's a demo
        - feature1: 
          text: Sponsors and Winners are broken
        - feature1: 
          text: Connect websockets for CONFIG.bidding
      icon: live
      technologies: HTML, CSS, PHP, JavaScript, Adobe Contribute compatibility, Photoshop, Illustrator
      link: https://auction-demo.firebaseapp.com
      completedyear: 2016
    - evandanadotcom:
      title: Previous evandana.com
      description: "Although fully functional and easy to update, the old version was recently abandoned to save money on unecessary hosting charges." 
      features: 
        - feature: 
          text: "XML and XSLT drove print (InDesign) and web (PHP) résumé workflows."
        - feature: 
          text: "Featured a D3.js interactive graph that highlighted my capabilities in web development, leadership, and design."
        - feature: 
          text: "Responsive design based on <a href=\"www.getskeleton.com\" target=\"_BLANK\">Skeleton V1.1</a>." 
        - feature: 
          text: "Linked to page with example code demonstrating and annotating current tech (at the time): HTML5, jQUERY, CSS3 & LESS, XML, PHP."
      icon: github
      link: https://github.com/evandana/website-2012
      completedyear: 2012
  workHistory:
    - work1:
      company: Sapient Global Markets
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2013
      duration: (2013 - Present)
      technologies: ES2015, AngularJS 1.x, Aurelia, Jenkins, Atomic Design, NodeJS, JSPM
      description: Delivering UI of valuable enterprise level web application with complex RESTful services. Ensuring maintainable code with hierarchy of class extensions, abstracted templates, and custom methods on the appropriate level.
    - work1:
      company: Putnam Investments
      location: Boston, MA
      title: Javascript UI Developer 
      started: 2012
      duration: (2012 - 2013)
      technologies: JavaScript (jQuery, Highcharts), CSS, HTML, Backbone.js, Modernizr, SVN
      description: Extended current app by developing additional functionality and engaging UI with JavaScript. Implemented significant contributions in an agile team to achieve business goals. Reached cross-browser functionality with collaborative discussions. 
    - work1:
      company: Innerscope Research Inc.
      collapsed: true
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2009
      duration: (2009 - 2012)
      technologies: HTML, CSS, PHP, JavaScript, Photoshop, Illustrator
      description: "Architected, implemented, and optimized dynamic internal web sites under tight time constraints. Increased efficiency through process refinement and custom application development; reduced bottle-necks. Satisfied clients by researching technical solutions, advising on options, and implementing solutions. Effectively managed graphic design interns with clear instruction and judicious direction; initiated the graphic design intern program, complete with cumulative curriculum. Conceptualized, designed, and coordinated delivery of graphical needs: marketing material, graphical information, and interactive experiences."
    - work1:
      company: EC Boston
      collapsed: true
      location: Boston, MA
      title: Web Developer 
      started: 2009
      duration: (2009)
      technologies: HTML, CSS, PHP, JavaScript, Adobe Contribute compatibility, Photoshop, Illustrator
      description: Facilitated and increased conversion rates by establishing new branding and easily accessible information. Worked closely with client to optimize content organization and modernize graphical feel for improved user experience. Content updatable by client without markup. Site was live September 2009 - 20011.
    - work1:
      company: Crimson Life Sciences
      collapsed: true
      location: Boston, MA
      title: Process Engineer 
      started: 2009
      duration: (2009)
      technologies: Java (apache.poi, javax.swing), Eclipse IDE, Microsoft Office (2001-2007), Mac and PC platforms
      description: "Delivered high ROI by automating Excel and Word document processing. Thoroughly examined current manual processes; using diagrams and concise summary, discussed proposed solution with project stakeholders. Achieved timely project completion through appropriate architecture and schedule planning. Resulting desktop Java application eliminated unnecessary user interaction and maximized efficiency, accuracy and ease of use."
    - work1:
      company: Reebok International
      collapsed: true
      location: Canton, MA
      title: Graphic Designer & Process Engineer 
      started: 2007
      duration: (2007 - 2009)
      technologies: "AppleScript, HTML, XML, CSS, PHP, FileMaker Pro, InDesign, Illustrator, Photoshop, Bridge"
      description: Improved efficiency and accuracy of artwork-data workflow by authoring scripts to remove repetitive tasks. Initiated projects to enhance data communication across groups. Saved resources by in-house development of a dynamic departmental website for collateral viewing and organization; crafted simple update process with existing database. Designed and built image- and data-intensive catalogs; coordinated and automated catalog production. 
  educationHistory:
    - rit:
      organization: Rochester Institute of Technology
      location: Rochester, NY
      degree: Bachelor
      major: Industrial Design
      completed: 2005
      duration: (2001 - 2005)
      description: "BFA in Industrial Design, GPA 3.84, highest honors. AAS in Graphic Design. Technical concentrations in Mechanical and Manufacturing Technology."
    - extension:
      organization: Harvard Extension School
      location: Cambridge, MA
      description: Mobile Operating Systems and Applications
      completed: 2013
      duration: (2013 - 2013)
    - coursera:
      organization: Coursera.org
      location: Stanford University Online
      description: "Enriching and expanding skills and understanding with classes: Introduction to Python & Model Thinking & Software Engineering for SaaS. Courses include homework, lectures, and quizzes/exams. Topics covered: Python, Ruby on Rails, SQL, Amazon Web Services, version control with GIT, and cloud deployment with Heroku. Earned a certificate of completion for listed classes."
      completed: 2014
      duration: (2012 - 2013)  
  activities:
    - activity:
      location: Boston, MA
      collapsed: true
      title: Co-leader of November Project's Boston Tribe
      started: 2013
      icon: bicycle
      duration: (2014 - 2015)
      description: "Continual learning about how to inspire self and others while designing, leading, coaching, and documenting workouts for 150-1500 athletes of all abilities. Developing comfort, ease, and power when speaking and writing for a large audience. Building strong relationships and learning how to give and recieve critical feedback with other co-leaders."
    - activity:
      location: General Assembly, MA
      title: D3.js Instructor 
      started: 2015
      icon: code
      duration: (2015)
      description: "Engaged developers in an immersive and interactive two-night class called Introduction to D3.js. Presented using a follow-along slide deck with individually-editable code examples: <a href=\"http://slides.com/evandana/d3-intro-3\" target=\"_BLANK\">http://slides.com/evandana/d3-intro-3</a>." 
    - activity:
      location: Boston, MA
      collapsed: true
      title: Co-leader and Webmaster of The Most Informal Running Club Ever (TMIRCE) 
      started: 2010
      icon: bicycle
      duration: (2010 - 2011)
      description: "Cultivated welcoming community of runners through attitude modeling and directing activities. Provided club necessities and member benefits through successfully managed sponsor relationships without losing sight of integrity. Positioned club for success with engaging summary presentation of social impact: digitally and physically."
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited Conversational
  programmingSkills:
    - skill1:
      name: JavaScript/ES2015
      percentage: 80%
      usefulness: expert
    - skill2:
      name: Frameworks - React/Angular
      percentage: 60%
      usefulness: experienced
    - skill3:
      name: CSS3/SCSS
      percentage: 70%
      usefulness: experienced
    - skill4:
      name: HTML5
      percentage: 70%
      usefulness: experienced
    - skill3:
      name: Server-side
      percentage: 30%
      usefulness: proficient
