# Site settings
title: Evan Dana's CV
description: Evan Dana's CV
favicon: /assets/img/edana-professional.jpg
baseurl: ""
url: http://evandana.github.io
rss_url: /pages/atom.xml
google_analytics: UA-6306273-2
resumelink: false

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Evan Dana
  title: JavaScript Developer
  address: Boston, MA
  email: userhatestogetspam@gmail.com
  link: http://evandana.com
  weibo:
  github: evandana
  linkedin: evandana
  twitter: evandana
  gavatar: /assets/img/edana-professional.jpg
  stackoverflow:
#  stackoverflow: 4582127
  intro: 
      firstline: >
        Front-end manager / UI lead developer with a focus on <a href="#work-sample-auction-app" title="Jump to Auction App (Work Sample)">architecting successful web experiences</a>. 
      description: >
        Approaches challenges with <a href="#activity-november-project" title="Jump to November Project (Activity)">engaging energy and passion</a>, 
        engineering <a href="#work-sample-evandanadotcom" title="Jump to Evandana.com (Work Sample)">efficient tooling, processes</a>, and <a href="#work-history-sapient" title="Jump to Publicis.Sapient (Work History)">organization to benefit the project and team</a>.
        <a href="#activity-ga-instructor" title="Jump to GA Instructor (Activities)">Articulate technical</a> and cross-domain communication enhanced by <a href="#education-history-rit" title="Jump to RIT (Education History)">design background</a>.
  workSamples:
    - auctionapp:
      id: auction-app
      title: PMC Auction App
      description: >
        From concept through development to processing results, this live-bidding auction web app exceeded expectations for learning experiences and funds raised. 
        Working with one other developer, we started with domain models, UX whiteboarding, framework choices, and hosting discussions.
        <br/><br/>
        <a href="https://auction-demo.firebaseapp.com" target="_BLANK">Try the demo-version <i class="fa fa-external-link"></i></a> using dummy data. 
      features: 
        - feature1: 
          text: Live bidding using websockets, ReactJS, and Redux
        - feature1: 
          text: Secure sign-in using Google OAuth
        - feature1: 
          text: Enforced bidding rules 
        - feature1: 
          text: Database and hosting using Firebase.io (experimented with AWS)
      icon: live
      technologies: "ReactJS 15.1.x, Redux, websockets, Firebase.io, Material-UI, Google OAuth, ES2015, Babel, Domain Modeling"
      link: https://auction-demo.firebaseapp.com
      completedyear: 2016
    - evandanadotcom:
      id: evandanadotcom 
      title: Previous evandana.com
      collapsed: true
      description: "Although fully functional and easy to update, the old version was recently abandoned to save money on unecessary hosting charges." 
      features: 
        - feature: 
          text: "XML and XSLT drove print (InDesign) and web (PHP) résumé workflows."
        - feature: 
          text: "Featured a D3.js interactive graph that highlighted my capabilities in web development, leadership, and design."
        - feature: 
          text: "Responsive, mobile-friendly and quick-to-load." 
        - feature: 
          text: "Linked to page with example code demonstrating and annotating current tech (at the time): HTML5, jQUERY, CSS3 & LESS, XML, PHP."
      icon: github
      technologies: "D3.JS, PHP, JavaScript, XML, XSLT, HTML5, CSS3, InDesign XML Workflow"
      link: https://github.com/evandana/website-2012
      completedyear: 2012
  workHistory:
    - work1:
      id: sapient
      company: Publicis.Sapient | Sapient Consulting
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2013
      duration: (2013 &ndash; Present)
      technologies: "ES2015, AngularJS 1.x, Aurelia, Agile, Atomic Design, JSPM, NodeJS, Continuous Integration, Hexagonal Architecture (server-side), Domain-Driven Development, Domain Modeling" 
      description: > 
        UI Lead and front-end developer with aptitude on team dynamics: group coordination, process efficiencies, and individual development. 
        Awarded recognition for Client-Focused Delivery after client feedback on project when leading FED with recently self-taught technology.
        <br/><br/>    
        Years of experience in UI lead role, conducting enganging technical presentations, and as technical liason for client and internal domain teams.
        Enforced code quality using best practices such as John DePapa's style guide and BEM on both Agile and Atomic approach projects. 
        Self-motivated and driven as exemplified by creation of D3.js library during bench time and initiation of effective team-building program.
        Advocate for code stability through unit, integration, functional, or automated visual-diff testing.
    - work1:
      company: Putnam Investments
      location: Boston, MA
      title: Javascript UI Developer 
      started: 2012
      duration: (2012 &ndash; 2013)
      technologies: JavaScript (jQuery, Highcharts), CSS, HTML, Backbone.js, Modernizr, SVN
      description: >
        Extended current app by developing additional functionality and engaging UI with JavaScript. 
        Implemented significant contributions in an agile team to achieve business goals. 
        Reached cross-browser functionality with collaborative discussions. 
    - work1:
      company: Innerscope Research Inc.
      collapsed: true
      location: Boston, MA
      title: Sr. Interactive Developer, L2 
      started: 2009
      duration: (2009 &ndash; 2012)
      technologies: HTML, CSS, PHP, JavaScript, Photoshop, Illustrator
      description: >
        Architected, implemented, and optimized dynamic internal web sites under tight time constraints. Increased efficiency through process refinement and custom application development; reduced bottle-necks. Satisfied clients by researching technical solutions, advising on options, and implementing solutions. Effectively managed graphic design interns with clear instruction and judicious direction; initiated the graphic design intern program, complete with cumulative curriculum. Conceptualized, designed, and coordinated delivery of graphical needs: marketing material, graphical information, and interactive experiences.
    - work1:
      company: EC Boston
      collapsed: true
      location: Boston, MA
      title: Web Developer 
      started: 2009
      duration: (2009)
      technologies: HTML, CSS, PHP, JavaScript, Adobe Contribute compatibility, Photoshop, Illustrator
      description: >
        Facilitated and increased conversion rates by establishing new branding and easily accessible information. 
        Worked closely with client to optimize content organization and modernize graphical feel for improved user experience. 
        Content updatable by client without markup. Site was live September 2009&nda &ndash; 20011.
    - work1:
      company: Crimson Life Sciences
      collapsed: true
      location: Boston, MA
      title: Process Engineer 
      started: 2009
      duration: (2009)
      technologies: Java (apache.poi, javax.swing), Eclipse IDE, Microsoft Office (2001-2007), Mac and PC platforms
      description: >
        Delivered high ROI by automating Excel and Word document processing. 
        Thoroughly examined current manual processes; using diagrams and concise summary, discussed proposed solution with project stakeholders. 
        Achieved timely project completion through appropriate architecture and schedule planning. 
        Resulting desktop Java application eliminated unnecessary user interaction and maximized efficiency, accuracy and ease of use.
    - work1:
      company: Reebok International
      collapsed: true
      location: Canton, MA
      title: Graphic Designer & Process Engineer 
      started: 2007
      duration: (2007&nda &ndash; 2009)
      technologies: "AppleScript, HTML, XML, CSS, PHP, FileMaker Pro, InDesign, Illustrator, Photoshop, Bridge"
      description: >
        Improved efficiency and accuracy of artwork-data workflow by authoring scripts to remove repetitive tasks. 
        Initiated projects to enhance data communication across groups. 
        Saved resources by in-house development of a dynamic departmental website for collateral viewing and organization; crafted simple update process with existing database. 
        Designed and built image- and data-intensive catalogs; coordinated and automated catalog production. 
  educationHistory:
    - rit:
      id: rit
      organization: Rochester Institute of Technology
      location: Rochester, NY
      degree: Bachelor
      major: Industrial Design
      completed: 2005
      duration: (2001 &ndash; 2005)
      description: >
        BFA in Industrial Design, GPA 3.84, highest honors. 
        <br/><br/>
        AAS in Graphic Design. 
        <br/>
        Concentration in conversational French. Technical concentrations in Mechanical and Manufacturing Technology.
    - extension:
      organization: Harvard Extension School
      location: Cambridge, MA
      description: >
        Mobile Operating Systems and Applications
        <br/><br/>
        Deep dive into hardware and software underlying Android and iOS operating sytems. 
        Covered spectrum of mobile landscape and considerations for design/development of web, native wrappers, and native apps.
        Final project: Android "deck of cards" workout app.
      completed: 2013
      duration: (2013 &ndash; 2013)
    - coursera:
      organization: Coursera.org
      location: Stanford University Online
      description: >
        Enriched and expanded skills and understanding with classes: Introduction to Python & Model Thinking & Software Engineering for SaaS. 
        Courses included homework, lectures, and quizzes/exams. 
        <br/></br/>
        Topics covered: Python, Ruby on Rails, SQL, Amazon Web Services, version control with GIT, and cloud deployment with Heroku. 
        Earned a certificate of completion for listed classes.
      completed: 2014
      duration: (2012 &ndash; 2013)  
  activities:
    - activity:
      id: november-project
      location: Boston, MA
      title: Co-leader of November Project Boston
      started: 2013
      icon: bicycle
      duration: (2014 &ndash; 2015)
      description: >
        November Project is a free-fitness movement with "tribes" in 30+ cities across the world, with Boston as the origin.
        <br/></br/>
        Developed comfort, ease, and power when speaking and writing for a large audience.
        Inspired self and others while designing, leading, coaching, and documenting workouts for 150-1500 athletes of all abilities.  
        With co-leaders, cultured strong relationships that included feedback cycles.
    - activity:
      id: ga-instructor
      location: General Assembly, MA
      title: D3.js Instructor 
      started: 2015
      icon: code
      duration: (2015)
      description: >
        Engaged developers in an immersive and interactive two-night class: Introduction to D3.js. 
        Presented using a <a href="http://slides.com/evandana/d3-intro-3" target="_BLANK">follow-along slide deck<i class="fa fa-external-link"></i></a>
         with individually-editable code examples.
    - activity:
      location: Boston, MA
      collapsed: true
      title: Co-leader and Webmaster of The Most Informal Running Club Ever (TMIRCE) 
      started: 2010
      icon: bicycle
      duration: (2010 &ndash; 2011)
      description: >
        Cultivated welcoming community of runners through attitude modeling and directing activities. 
        Provided club necessities and member benefits through successfully managed sponsor relationships without losing sight of integrity. 
        Positioned club for success with engaging presentation of its social impact.
  REMOVE-THIS-TO-ENABLE-languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited Conversational
  programmingSkills:
    - skill1:
      name: JavaScript/ES2015
      percentage: 80%
      usefulness: expert
    - skill2:
      name: "Frameworks: React | Angular | Aurelia"
      percentage: 60%
      usefulness: experienced
    - skill3:
      name: CSS3/SCSS
      percentage: 70%
      usefulness: experienced
    - skill4:
      name: HTML5
      percentage: 70%
      usefulness: experienced
    - skill3:
      name: Server-side
      percentage: 30%
      usefulness: proficient
  opensource:
      intro: Notable repos
      repos:
      - repo:
        name: Auction App - Demo Version
        link: https://github.com/evandana/auction-demo
        description: Demo version of full app. Uses updated versions of React, Material-UI, etc.
      - repo:
        name: PMC Auction App
        link: https://github.com/evandana/pmc-auction
        description: App used for live auction.
      - repo:
        name: Repo for this site
        link: https://github.com/evandana/evandana.github.io
        description: Jekyll template with UX modifications.
      - repo:
        name: Learning Programming Patterns (notes)
        link: https://github.com/evandana/learning-programming-patterns
        description: Notes taken while studying programming patterns.
